### ISSUE TITLE
能否不依赖 makit

### ISSUE THREAD

**Issue by l5oo00** [searchfe/fis-http-push#9]
使用此包时， 如果没有同时使用 makit， 编译期会报错， 具体是这一行： 

https://github.com/searchfe/fis-http-push/blob/8f269350fc762fbf121652d56f0d80bcb107058d/src/index.ts#L3

能否让此包不依赖 makit？

**Comment by harttle** [comment]
应该是只依赖这样的接口（如果没有，默认用 console.log）：

```typescript
interface Logger {
    pause(): void
    resume(): void
    log(...args: any[]): void
}
```
